### ISSUE TITLE
After sign up issue

### ISSUE THREAD

**Issue by HetviSoni** [meshery/play#105]
#### Current Behavior
After the user signs up, the sign up button still appears on the screen.

![image](https://user-images.githubusercontent.com/76479104/236681585-dcc01d0e-c31c-47e0-bc90-ecf5fb592cc1.png)

#### Expected Behavior
The button should disappear after successful signup.
 I would like to work on this issue.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by thisiskaransgit** [comment]
Thank you for raising this issue, please go ahead and fix it :rocket:

**Comment by arunavabasu-03** [comment]
Hey, I would like to work on this!!

**Comment by HetviSoni** [comment]
I have made the changes. Can u please review @thisiskaransgit

**Comment by HetviSoni** [comment]
Hey @thisiskaransgit I opened a pr for this issue months ago and it's also approved.  It would be helpful if is merged or if any other changes are required, please suggest
