### ISSUE TITLE
We can add more frequently asked questions

### ISSUE THREAD

**Issue by Nitishupkr** [meshery/play#111]
#### Current Behavior
there are limited questions in the frequently asked questions

#### Desired Behavior
we can add more questions in frequently asked questions so it will be easy for the users to solve their issues and clear their doubts

#### Implementation
we can add this type of questions :-
How can I contribute to the Meshery open-source project?
What kind of support options are available for Meshery users?
How does Meshery help with service mesh management and performance testing?
and we can add many more

#### Mockups
![meshery2](https://github.com/meshery/play/assets/95420063/f9605337-4423-4580-9e90-ecc09cce5b89)

Are you working on this issue?
Yes

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by itsarraj** [comment]
@leecalcote Do we have to add any more FAQ?

**Comment by deepchauhan2002** [comment]
Hi @Nitishupkr I want to work on this issue?

**Comment by alphaket14** [comment]
Hi I want to suggest these faq questions, hope you find them useful


Question 1:
What is Meshery Cloud Native Playground and how can it benefit developers?

Answer:

- Meshery, a platform for self-service engineering, enabling collaborative design and management of cloud native infrastructure.
- This means developers can experiment, test, and validate their cloud native applications in a safe and controlled environment.
- Additionally, Meshery Cloud Native Playground promotes collaboration among developers. It allows multiple team members to work together on the same infrastructure, facilitating seamless communication and knowledge sharing.

Question 2:
How does Meshery enhance the performance of workload and service mesh in cloud native environments?

Answer:
Meshery's Cloud Native Performance Management feature improves the performance of workloads and service meshes by providing characterization capabilities. It integrates with Prometheus and Grafana, allowing developers to effectively monitor and analyze performance metrics. This helps optimize the performance and ensure efficient operation of cloud native applications.

Question 3:
How does Meshery's Data Plane Intelligence feature leverage WebAssembly filters for Envoy to enhance cloud native applications?

Answer:
By allowing the registry and configuration of these filters, Meshery enables developers to extend the capabilities of Envoy and enhance functionalities such as security, traffic management, and observability in their cloud native applications.

Question 4:
How does Meshery simplify provisioning and workload onboarding in cloud native environments?

Answer:
It offers streamlined processes and tools for efficiently setting up and deploying cloud native applications. This enables developers to quickly onboard workloads, saving time and effort in the deployment phase of the application lifecycle.

Cheers

**Comment by malaviya-parth** [comment]
If the questions suggested by @alphaket14 need to be added the website then I would like to do that.

**Comment by Yagi91** [comment]
Hello @Nitishupkr can you assign this to me?

**Comment by hemantmm** [comment]
Hi, @Nitishupkr can I start working on this issue?

And can add questions suggested by @alphaket14.

**Comment by hemantmm** [comment]
Hi, @vishalvivekm can I work on this issue?
And the questions suggested by @alphaket14
