### ISSUE TITLE
In footer text alignment is different in meshery.io & play.meshery.io

### ISSUE THREAD

**Issue by inviBeast** [meshery/play#112]
Screenshot
<img src="https://github.com/meshery/play/assets/99094157/b0c40325-2378-4a8d-9989-1cb970cc2d6a" width="250" height="400">
<img src="https://github.com/meshery/play/assets/99094157/a0e3eeda-bdc9-4c38-9ba8-e3e9cc697ad5" width="250" height="400">

Description
Responsive Issue:
The footer in meshery.io is looking more professional and well-designed whereas in the case of play.meshery.io it's not looking uniform and appealing.

Desired
The footer design of meshery.io should be used in  play.meshery.io

**Comment by inviBeast** [comment]
@leecalcote can I work on this issue?

**Comment by Nikhil-Ladha** [comment]
The center-alignment of the footer is desired. If anything, meshery.io's footer could be center-aligned as well

**Comment by inviBeast** [comment]
Ok ,Thank you.
