### ISSUE TITLE
There can be some margin after the <h2>Meshery Playground</h2> tag.

### ISSUE THREAD

**Issue by ankur0904** [meshery/play#113]
#### Current Behavior

![1](https://github.com/meshery/play/assets/98346896/7b15e222-927e-43ed-82a2-41d80b32ac19)

#### Expected Behavior

![2](https://github.com/meshery/play/assets/98346896/5c2cf299-2170-41e4-9eac-6a81a4fc2258)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by SoumyadeepOSD** [comment]
@ankur0904 I'm new to this community..let me work on this issue

**Comment by ankur0904** [comment]
@Chadha93  @vishalvivekm  What are your thoughts about this issue?

**Comment by itsarraj** [comment]
this is not a bug this is enhancement
