### ISSUE TITLE
Issue Template Updates for Figma link

### ISSUE THREAD

**Issue by leecalcote** [meshery/play#128]
#### Current Behavior
The project's current issue templates are missing an open invitation link where new contributors can join the community's Figma team and view user interface designs and other UX projects.

#### Desired Behavior
Each template that has a reference to Figma in its resources section should an invite link added.

#### Implementation

In each [issue template](../blob/master/.github/ISSUE_TEMPLATE/) that refers to Figma, replace the current line referring to Figma with this line:

```
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)```
```
#### Acceptance Tests
1. All references to Figma include the "open invite" link.
---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by leecalcote** [comment]
Thanks, @depleur 👍

**Comment by Saurabhmahto** [comment]
If the issue is still not solved please assign me.

**Comment by thisiskaransgit** [comment]
@Saurabhmahto, you might want to look for an unassigned issue [here](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22)
