### ISSUE TITLE
Changing to new Twitter X Logo

### ISSUE THREAD

**Issue by malaviya-parth** [meshery/play#138]
#### Current Behavior
![image](https://github.com/meshery/play/assets/82119640/51162be8-0d21-48c6-94e5-07d889454d9a)

#### Desired Behavior
![image](https://github.com/meshery/play/assets/82119640/a032fd21-92e8-45da-a026-fd3a51281e02)

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by thisiskaransgit** [comment]
@malaviya-parth, sure go ahead 🚀

**Comment by abhishekmmgn** [comment]
Hey, there!
I would like to work on this. This is a small contribution but it would mean a lot to me. I've already done change on local, pull request part left. Kindly assign this to me.

**Comment by thisiskaransgit** [comment]
Hey @malaviya-parth, Let's discuss it on the website call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by Yagi91** [comment]
Hello! @malaviya-parth 
I would like to be assigned to this. I am a newcomer and this will really help as a first task.

**Comment by ManishKapoor5** [comment]
Hi @malaviya-parth 
I have done the changes but while pushing it. It is showing error.

remote: Permission to meshery/play.git denied to ManishKapoor5.
fatal: unable to access 'https://github.com/meshery/play.git/': The requested URL returned error: 403

**Comment by captain-Akshay** [comment]
can i work on this?
@ManishKapoor5 ?
