### ISSUE TITLE
[Grammar Adjustment] Learn - content next to the "Get Early Access" form

### ISSUE THREAD

**Issue by sandramsc** [meshery/play#151]
**Current State:**

- Link to website: https://play.meshery.io/
- Currently, the text reads as follows: "Sign-up to receive a user account, entitled with perpetually free and full access the Playground environment."

**Desired State:**

- The suggested change is to add the word _to_ so it reads: "Sign-up to receive a user account, entitled with perpetually free and full access to the Playground environment."

---
**Screenshot**
![mesh](https://github.com/layer5io/layer5/assets/19821445/8619c001-0175-46d2-af9f-b472a55a56f6)

**Comment by sandramsc** [comment]
@VivekBaldha0712 Consider requesting re-assignment here

**Comment by VivekBaldha0712** [comment]
Sure. I would like to work on this issue.

**Comment by palash018** [comment]
Can, I work on this i have already made changes locally if you allow i will submit a pull request @sandramsc

**Comment by abhijeetgauravm** [comment]
> CC: @abhijeetgauravm @VivekBaldha0712 Consider requesting re-assignment here

Can u assign him @Mohith234 ?

**Comment by sandramsc** [comment]
> Can, I work on this i have already made changes locally if you allow i will submit a pull request @sandramsc also changes not only needs to be made on the page but also on FAQ answers as well it also has same text

 Hi, issues are assigned on a first come first serve basis to be fair to all contributors in the community, it's great that you're eager to contribute, however, one needs to ask for an issue to be assigned to them first, and then start working on it. Let's focus on collaboration first and not competition. If you haven't already, take a look at the contributing guidelines [here](https://layer5.io/community/newcomers), particularly the section on "Finding an Issue to Work On".
