### ISSUE TITLE
[UX - Responsiveness] Learn - text alignment not consistent

### ISSUE THREAD

**Issue by sandramsc** [meshery/play#155]
### Current Behaviour

- Link to website: https://play.meshery.io/
- The paragraph text under "The Cloud Native Playground" is center aligned
- However the text under "Sign-up to receive a user account..." is left aligned, additionally, the subheading under "Frequently Asked Questions" is also left aligned.

#### Screenshots

![su](https://github.com/layer5io/layer5/assets/19821445/4f8b370b-0232-4b02-b8ae-5dc9e3cd1a30)
![fqa](https://github.com/layer5io/layer5/assets/19821445/4e957960-d23a-4c31-906f-1abfc9eb0153)

### Suggested Behaviour
- To maintain design consistency text should have the same format i.e either left aligned or center aligned.

#### Screenshots

![mp](https://github.com/layer5io/layer5/assets/19821445/70d23f48-746e-41f7-bc11-eb929ca8aacd)
![su](https://github.com/layer5io/layer5/assets/19821445/14b9406d-cf77-4ce0-9aef-3ee44783ceb4)

### Environment:
- Host OS: Mobile responsiveness
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by r0nz-29** [comment]
Can I work on this issue? 
@sandramsc

**Comment by rahulrana701** [comment]
hi @sandramsc I would like to work on this issue , so could you please assign it to me.

**Comment by r0nz-29** [comment]
Thanks @Mohith234 
I have linked my PR, let me know if it needs any changes

**Comment by r0nz-29** [comment]
Created a new PR to include latest changes from play/master.

**Comment by Raj100679** [comment]
Hey @sandramsc , Is this issue open I would love to work on this

**Comment by ayusudi** [comment]
Hi @sandramsc, I would like to work on this. Thank you

**Comment by sandramsc** [comment]
@ayusudi I have assigned this to you.

**Comment by ayusudi** [comment]
Hi @sandramsc , it's already done. Thank you
