### ISSUE TITLE
Create the Cloud Native Playground

### ISSUE THREAD

**Issue by leecalcote** [meshery/play#16]
#### Overview
Hosted at play.meshery.io, build a unique learning environment for learning modern application networking through Meshery's support of every service mesh, orchestration of Kubernetes, and integration with many other CNCF projects. Meshery's genesis is that of helping teach people about service mesh technology and enabling to operate this type of cloud native infrastructure confidently. The proposed project is aimed at furthering this mission with interactive API documentation connected to a cloud native playground (a running instance of Meshery).

#### Mockups

<p align="center"><img src="https://raw.githubusercontent.com/meshery/play/master/.github/readme/images/meshery-playground.png" width="80%" />

See https://layer5.io/programs/lfx for details.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by MayankMittal1** [comment]
Hey @leecalcote I'm interested  in this project for Lfx summer mentorship program, please guide me for getting started

**Comment by leecalcote** [comment]
> Hey @leecalcote I'm interested in this project for Lfx summer mentorship program, please guide me for getting started

Good of you to join the community Slack. I've provided many details there.
