### ISSUE TITLE
[BUG] Footer elements is not aligned

### ISSUE THREAD

**Issue by GOKULNATH-RS** [meshery/play#163]
#### Current Behavior

The Footer elements were aligned properly in desktop and tab version but not in mobile, the elements were aligned center in mobile view.

#### Expected Behavior

 The Footer elements in mobile view should be aligned like in desktop and tab versions

#### Screenshots/Logs

**Current Behavior**
![mesher play footer dis-align](https://github.com/meshery/play/assets/114755342/fed5c241-a879-4540-818c-51dfb51e9cca)

**I would love to work on this issue** 👍 

#### Environment

- **Host OS:**  Windows

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by GOKULNATH-RS** [comment]
I would love to work on this issue if anyone assign me with this issue.

**Comment by hemantmm** [comment]
Hi, @leecalcote I would love to work on this issue.

**Comment by leecalcote** [comment]
I appreciate the thought. We are just spinning our wheels here, though. Let’s find other issues to work on.
