### ISSUE TITLE
Inconsistent Design on Dropdown component across various pages.

### ISSUE THREAD

**Issue by Iamrushabhshahh** [meshery/play#183]
#### Current Behavior

- The round border pattern generally creates a relaxed user experience across elements, but it feels awkward and out of place for FAQ dropdowns. 
- This issue persists across multiple pages due to the consistent use of the same component. 
- Additionally, the dropdown's behavior is inconsistent when active, regardless of light or dark mode. 

#### Expected Behavior

> This should be the Design For Light And Black Theme

![image](https://github.com/meshery/play/assets/96313281/db8ca478-dbc4-4ee1-99d9-8eea3f86acb1)
![image](https://github.com/meshery/play/assets/96313281/5d542f98-ec22-489e-a197-8058e534baa4)

#### Screenshots/Logs

![image](https://github.com/meshery/play/assets/96313281/a6ed72c1-9b37-4827-b7a2-9d42c294d261)

> This shows Design it has Right Now

![image](https://github.com/meshery/play/assets/96313281/2cbb0141-4dcb-40f5-abf0-88baf10fdaf8)
![image](https://github.com/meshery/play/assets/96313281/944a3aba-bb62-4898-b9fe-971eb69cc109)

Body part of dropdown can be clerly high lighted so user can gues it's dropdown area.

#### Environment

- **Host OS:**  Windows 
- **Platform:** Chrome Browser

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Iamrushabhshahh** [comment]
@leecalcote  Not able to add labels please add Ui/Ux Labels.

**Comment by Iamrushabhshahh** [comment]
@leecalcote can you add lavel of ui in this and also assign it.

**Comment by leecalcote** [comment]
Assign it to whom?

**Comment by leecalcote** [comment]
@Iamrushabhshahh, I appreciate you raising this issue. Perhaps, you're right, but we're just spinning our wheels here. This isn't worth the time. We spent gobs and gobs of time on every pixel in other UIs where doing so is worth the time (e.g. MeshMap and meshery.io), but we have so many other websites that keeping track of new contributors and helping them as they inevitable bring in bugs just isn't worth the time. Let's find you another qualified issue to work on.

**Comment by leecalcote** [comment]
Also, your assignment on other open issues like this one https://github.com/meshery/play/issues/181 isn't complete, yet, so let's get you finishing what you volunteer for first, before giving you another one to sit on.

**Comment by Iamrushabhshahh** [comment]
Sure , Done with  [$181](https://github.com/meshery/play/issues/181) will close it soon.
