### ISSUE TITLE
To remove the italic effect from a text on Playground page

### ISSUE THREAD

**Issue by Aviral0702** [meshery/play#199]
#### Current Behavior
The text "Meshery Playground" is written in italics just before the accordion of information. It breaks the consistency of the design of the text which was followed since start of the page and looks off the wall
![image](https://github.com/meshery/play/assets/134831178/bc5e7796-c1b2-41c8-98e1-62d692889b34)

#### Desired Behavior
The desired behavior should consist of the text to be as consistent as all the piece of texts which is to be non-italic which will look more formal and give the boost of consistency to the page.
![image](https://github.com/meshery/play/assets/134831178/01092bee-a9fa-49e9-92bd-6b5b62acdc08)

#### Implementation
To approach this issue I will search for the part  of code where the text is formatted to be italic and will rectify the code. 

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by ayushrakesh** [comment]
@Aviral0702 Can I take this issue if you're not available.

**Comment by Sulochan-khadka** [comment]
Sorry for the inconvenience . Just added sign to the commits in the second PR.

**Comment by Ashparshp** [comment]
@Sulochan-khadka Could everyone please avoid creating pull requests until officially assigned to an issue? Your cooperation is greatly appreciated!

**Comment by THEBOSS0369** [comment]
Hey @ayushrakesh can you assign this to me! I can fix this.

**Comment by leecalcote** [comment]
Folks, the italic text is intentional and aid in offsetting one section from the next.
