### ISSUE TITLE
Dark/Light Mode and Signup Button Not Visible in Mobile View

### ISSUE THREAD

**Issue by akshansh-modi** [meshery/play#203]
#### Current Behavior
In the desktop view, the dark/light mode toggle and the signup button are visible. However, when switching to the mobile view, these options disappear. Upon inspecting the code, it appears that the display for these elements is set to none in the mobile view.

#### Expected Behavior
The dark/light mode toggle and signup button should be visible in both desktop and mobile views.

#### Screenshots/Logs
Mobile View(Actual):
![image](https://github.com/meshery/play/assets/92106389/ae6ff5ac-364e-4cc0-b12f-5d999859295f)
![image](https://github.com/meshery/play/assets/92106389/e385615b-5604-47b6-a979-061a3f174432)

Mobile View(Expected):
![image](https://github.com/meshery/play/assets/92106389/8a75e896-3618-4ea5-a760-6339b6400220)
![image](https://github.com/meshery/play/assets/92106389/448e873a-abbb-4d5f-a767-a8ce41de90c4)
![image](https://github.com/meshery/play/assets/92106389/acaddfaf-1781-4531-a18a-a1e81ef794e8)

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by akshansh-modi** [comment]
Hi, I would like to work on this issue. Could you please assign it to me?
I have read the `CONTRIBUTING.md` and have set up a functional development environment.

**Comment by Ashparshp** [comment]
This issue persists, and you can start working on it. I will ask someone to assign it to you.
@leecalcote

**Comment by akshansh-modi** [comment]
@Ashparshp , I've resolved the issue. The next step is to create a pull request. Should I proceed with that, or should I wait first for someone to assign me the issue?

**Comment by leecalcote** [comment]
Thank you for validating, @Ashparshp

**Comment by akshansh-modi** [comment]
Please review the changes and provide feedback. Let me know if any further adjustments are needed.
