### ISSUE TITLE
Deprecated Usage of window.pageYOffset

### ISSUE THREAD

**Issue by akshansh-modi** [meshery/play#205]
#### Current Behavior
The codebase currently utilizes window.pageYOffset, which is deprecated in favor of window.scrollY for accessing the vertical scroll position of the document. It's recommended to update the codebase to use window.scrollY instead to ensure compatibility and future-proofing.

#### Expected Behavior
Update the codebase to use window.scrollY instead of window.pageYOffset.

#### Code Location
play\site\src\components\Navigation\index.js

#### Screenshots/Logs
![image](https://github.com/meshery/play/assets/92106389/e5f4b23e-8dc0-4ade-8e7b-c181b2bc1566)

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by akshansh-modi** [comment]
Hi, I would like to work on this issue. Could you please assign it to me?

**Comment by Ashparshp** [comment]
Thanks for addressing this! But Ensure compatibility with our React and dependencies versions..

**Comment by akshansh-modi** [comment]
@Ashparshp 
Please review the changes and provide feedback. Let me know if any further adjustments are needed.
