### ISSUE TITLE
Remove the signup form

### ISSUE THREAD

**Issue by Ashparshp** [meshery/play#214]
#### Current Behavior
we have signup form.

#### Expected Behavior
remove the signup form on https://play.meshery.io/

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by aryannargotra** [comment]
Can you assign me this issue

**Comment by Ashparshp** [comment]
@vishalvivekm, has it been fixed?

**Comment by vishalvivekm** [comment]
> @vishalvivekm, has it been fixed?

There's a pr up. would you be kind enough to review it?
