### ISSUE TITLE
[Site] Create Dark Mode for Website

### ISSUE THREAD

**Issue by leecalcote** [meshery/play#26]
#### Current Behavior
This single page site only supports light mode and has no mode switcher. 

#### Desired Behavior
This single page site should be using the same dark mode colors and dark mode switcher as the layer5.io site is. 

#### Implementation
See https://layer5.io/brand for resources and https://github.com/layer5io/layer5 for it’s dark mode colors. 

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by thisiskaransgit** [comment]
hey @leecalcote I would like to work on this issue
