### ISSUE TITLE
[Site] Form is not mobile responsive

### ISSUE THREAD

**Issue by Chadha93** [meshery/play#28]
#### Current Behavior
![image](https://user-images.githubusercontent.com/65453826/202249884-0126de5f-3f67-4bdf-9e7d-91ff2b7bd9b9.png)

#### Expected Behavior
Make the form responsive across every breakpoint.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by gogoiakash2311** [comment]
@Chadha93 Can you assign this to me?

**Comment by Chadha93** [comment]
> @Chadha93 Can you assign this to me?

Sure.

**Comment by gogoiakash2311** [comment]
@Chadha93 Not able to run the site locally. Can you please guide me in setting up the project locally?

**Comment by Chadha93** [comment]
> @Chadha93 Not able to run the site locally. Can you please guide me in setting up the project locally?

@gogoiakash2311 You can use `make setup-libs` then `make site`. See the makefile. Yes we also need to add these instruction in contribution.md.

**Comment by AnnuCode** [comment]
Hi @gogoiakash2311, if it's okay with you, can I work on this issue?

**Comment by gogoiakash2311** [comment]
Heyy @AnnuCode I'm already working on this issue.

**Comment by gogoiakash2311** [comment]
@AnnuCode I have seen that you have already made a PR for this issue. Go for it. I'm unassigning myself from this issue.

**Comment by AnnuCode** [comment]
@gogoiakash2311 I mistakenly started working on this issue without noting that you have already been assigned this issue. So please go ahead and make the contribution :)

**Comment by gogoiakash2311** [comment]
Okay!! then thanks

**Comment by gogoiakash2311** [comment]
Preview for the issue #28 at: https://tangerine-raindrop-15674c.netlify.app/
@Chadha93  Let me know if any changes are required.
After that, I'll make a PR

**Comment by gogoiakash2311** [comment]
Hey @Chadha93 I have made a PR #31 for this issue

**Comment by UtkarshMishra12** [comment]
@gogoiakash2311 It's still not responsive below 300px 👀 [Link](https://tangerine-raindrop-15674c.netlify.app/)

**Comment by UtkarshMishra12** [comment]
@gogoiakash2311 Let me know if you need any help. 😊

**Comment by gogoiakash2311** [comment]
Sure

**Comment by Nikhil-Ladha** [comment]
> @gogoiakash2311 It's still not responsive below 300px eyes [Link](https://tangerine-raindrop-15674c.netlify.app/)

TBH, we don't need to be responsive below 300px. I don't think there is any device having that low of a resolution and even if so, we can safely ignore it. Not a big deal.

**Comment by gogoiakash2311** [comment]
@Nikhil-Ladha I'll do that in the current PR itself
