### ISSUE TITLE
Correct the spelling of the "curriculum" on Main page

### ISSUE THREAD

**Issue by UtkarshMishra12** [meshery/play#37]
#### Current Behavior

Correct the spelling of the "curriculum"

#### Expected Behavior

ciricullum -> "curriculum"

#### Screenshots/Logs

![image](https://user-images.githubusercontent.com/67385503/207593227-ee96659e-0bc0-492e-8713-9e7649fa7dad.png)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by PanyalaSainathReddy** [comment]
@UtkarshMishra12 can you assign me this issue

**Comment by UtkarshMishra12** [comment]
@leecalcote @Krishna2323 @Harshit-Dandriyal  Please assign it to @PanyalaSainathReddy

**Comment by Krishna2323** [comment]
@UtkarshMishra12, I don't have access to this repo.

**Comment by leecalcote** [comment]
> @UtkarshMishra12, I don't have access to this repo.

@Krishna2323 try again and let me know if that is still the case.
