### ISSUE TITLE
fix: fix Slack links in the footer

### ISSUE THREAD

**Issue by abhilipsasahoo03** [meshery/play#41]
#### Current Behavior

The Slack links (under Community and Socials section) in the footer take to 404 page and Service Mesh Interface page respectively.

#### Expected Behavior

The links should direct to the official Slack of Meshery.

#### Screenshots/Logs

![Screenshot_2022-12-16-18-31-33-565_com.github.android.jpg](https://user-images.githubusercontent.com/80174214/208104878-3dfa17f2-8a99-467a-8cb9-4e15a196f19c.jpg)
![Screenshot_2022-12-16-18-32-12-687_com.android.chrome.jpg](https://user-images.githubusercontent.com/80174214/208104888-1b45f3e1-29a5-47b0-a621-e7aa74254aa6.jpg)
![Screenshot_2022-12-16-18-32-19-034_com.android.chrome.jpg](https://user-images.githubusercontent.com/80174214/208104899-89fa16e2-d8dd-4d7b-8bcd-1d709cfc2588.jpg)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

@leecalcote I'd like to work on this issue. Kindly assign.

**Comment by leecalcote** [comment]
@abhilipsasahoo03 thank you for filing this issue. 👏

**Comment by abhilipsasahoo03** [comment]
> @abhilipsasahoo03 thank you for filing this issue. 👏 

Sure I'll work on it!
