### ISSUE TITLE
[Docs] Documentation of new dark mode needed

### ISSUE THREAD

**Issue by leecalcote** [meshery/play#51]
#### Current State
Dark and light mode support on the play.meshery.io site is new and undocumented.

#### Desired State
The [Contributing.md](https://github.com/meshery/play/blob/master/CONTRIBUTING.md) should answer the following questions (and more):
1. How does the site theming work?
1. How to define new classes / new styles that have both light and dark mode definitions?

Consider copying or referencing the https://github.com/layer5io/layer5 dark mode instructions.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Shivam-AfA** [comment]
@leecalcote Kindly review.
