### ISSUE TITLE
Adding LinkedIn Social media icon to the footer 

### ISSUE THREAD

**Issue by UtkarshMishra12** [meshery/play#55]
#### Current Behavior

The footer does not have a LinkedIn social icon 

#### Expected Behavior

Add LinkedIn social icon to the footer 

#### Screenshots/Logs

Now: 
![image](https://user-images.githubusercontent.com/67385503/211892468-8dac916e-0c80-4ee1-88df-b39d65ae07b6.png)

Desired state:
![image](https://user-images.githubusercontent.com/67385503/211892578-1ea8b609-d5f3-412b-b985-16edfd8cd602.png)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by avikt18** [comment]
Ready to take this one 🫡

**Comment by c00kie123** [comment]
I am interested in this as well! Let me know if this has been done

**Comment by c00kie123** [comment]
Done! PR #57

**Comment by avikt18** [comment]
I guess @c00kie123 has solved the issue @UtkarshMishra12
