### ISSUE TITLE
visual allignment inconsistency on homepage 

### ISSUE THREAD

**Issue by avikt18** [meshery/play#56]
#### Current Behavior
The home page of [Meshery Playground](https://play.meshery.io/) has some text centre aligned while some left aligned which makes the UI weird.

#### Desired Behavior 
The paragraphs should also be centre-aligned like the headings.

#### Screenshots
![image](https://user-images.githubusercontent.com/56340999/211905959-db1e4230-f36d-4d01-8026-7cb05db9f84b.png)

![image](https://user-images.githubusercontent.com/56340999/211905649-0722aa7b-df9d-416f-bd2d-613a83f68268.png)

#### Environment

- **Host OS:** Linux 
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thanks, @avikt18 👍 Please have a look at the positioning of the sun/moon (light/dark) theme switcher, too.
