### ISSUE TITLE
[Site] Navbar overflows and creates gaps below 500px screen width

### ISSUE THREAD

**Issue by Avi-88** [meshery/play#59]
#### Current Behavior
![bug1](https://user-images.githubusercontent.com/79744258/213908760-46cc9798-ff06-4d81-8fa9-2b81966dfa88.png)

#### Expected Behavior
![fixed1](https://user-images.githubusercontent.com/79744258/213908765-2e4b4818-1607-4db7-8a49-47c8631db9be.png)

#### Environment

- **Host OS:**  Linux 
- **Platform:** 
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Avi-88** [comment]
Hi, if anyone could assign me this I can create a quick PR. Also this is my first time creating an issue, so feel free to correct any mistakes

**Comment by UtkarshMishra12** [comment]
Thanks @Avi-88 here you go 🚀

**Comment by Avi-88** [comment]
Sorry for the delay , I made the PR but forgot to link it.
