### ISSUE TITLE
Incorporate promo video into site

### ISSUE THREAD

**Issue by leecalcote** [meshery/play#61]
#### Current Behavior
A new promotional video has been created for Meshery Playground - https://youtu.be/Do7htKrRzDA

#### Desired Behavior
Prominently present this video to site visitors.

#### Implementation
1. Allow Have this video play onclick of the site's large screenshot.
1. Add a "play" icon on top of the site's screenshot, so that users understand that a video will load on click.
1. The video should be embedded either directly in the page or be presented in a modal.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by Yh010** [comment]
can I work on this issue?

**Comment by leecalcote** [comment]
Sounds good, @Yh010

**Comment by Yh010** [comment]
@leecalcote should the video be played only on Yt, or also on platforms like Vimeo, Dailymotion?
Asking this to ensure whether the video should be directly embedded or by using a video player library like video.js

**Comment by leecalcote** [comment]
Thanks for doublechecking. Embedded via YouTube is both as simple and as complex as it needs to be. That is all that we’re looking for.

**Comment by Yh010** [comment]
needed some clarification:
1. didn't understand, "site's large screenshot"

**Comment by leecalcote** [comment]
The one and only screenshot on the single web page of this site.

**Comment by leecalcote** [comment]
Heads-up, @Yh010: this is a relatively simple item that we need completed quickly. If you’re unable to PR this today, that’s fine, but we’ll need to reassign.

**Comment by Yh010** [comment]
@leecalcote yup u can unassign me

**Comment by leecalcote** [comment]
Thanks for letting me know, @Yh010
