### ISSUE TITLE
[CI] First-time contributor welcome comments and celebration

### ISSUE THREAD

**Issue by leecalcote** [meshery/play#62]
#### Current Behavior
The community's standard first-time issue / pr welcoming comments and celebration is either missing or disabled.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by 0xSaksham** [comment]
I see no one working on this, should I give it a try?

**Comment by josephmidura** [comment]
Yes, go ahead and give it a try.

**Comment by senali-d** [comment]
@leecalcote I would like to work on this issue
