### ISSUE TITLE
[Site] Update navbar for mobile screens

### ISSUE THREAD

**Issue by Avi-88** [meshery/play#64]
#### Current Behavior

Currently the navbar remains same throughout all screen sizes and looks a bit cramped for smaller screens.
![dark-old](https://user-images.githubusercontent.com/79744258/215256641-c9dc7b12-7605-4910-9f3b-5f281c9a342f.png)

#### Desired Behavior
For screens  below 500px the navbar will have a sort of hamburger menu.

![dark-new-open](https://user-images.githubusercontent.com/79744258/215256703-06c97c9a-5be5-4518-a240-09f423bd5dd6.png)

#### Implementation
I was thinking about moving the entire navbar into its own navigation component. While the theme state will remain in app.js we can use props to pass and change its value from inside navigation component. If there is any other approach to this please let me know.

#### Mockups

![light-new-nav](https://user-images.githubusercontent.com/79744258/215256894-a2f25c08-531f-4980-abe5-bc0af85a178d.png)
![light-new-open](https://user-images.githubusercontent.com/79744258/215256905-4082d371-d846-4f49-beb3-1d096d61d6fd.png)

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by Avi-88** [comment]
Hi @leecalcote , sorry for the delay. Can you please share your thoughts on this and assign me this issue as well. I'll start working on the PR, thanks

**Comment by leecalcote** [comment]
Good work on the proposal and on the quality of these mockups, @Avi-88. 

@Nikhil-Ladha, here’s a proposal for your consideration.

**Comment by Yh010** [comment]
can i also work on  this issue along with @Avi-88 ?

**Comment by Avi-88** [comment]
Hi @Yh010 , I'm actually done with the changes that I proposed in the mockups currently waiting for the proposal to get accepted so i can make a PR. If you have a different design in mind I would be happy to help in making a new proposal, thanks

**Comment by Avi-88** [comment]
Hi @Yh010 , I was suggesting you to make a proposal with mockups having a different approach than the one I proposed as it will be easier to review the proposal and finalize a approach. I dont know exactly what happened but your PR seems to have multiple duplicate file changes. It would be better if you could link a PR that specifies the approach you are suggesting along with some mockups of the actual design, thanks
