### ISSUE TITLE
Creating a set of FAQs to be displayed on "play.meshery.io"

### ISSUE THREAD

**Issue by roopeshsn** [meshery/play#67]
#### Desired Behavior
Creating a set of FAQs to be displayed on [play.meshery.io](http://play.meshery.io/). The FAQs component for this can be borrowed from the [layer5.io](http://layer5.io/) website.

#### Mockups
[layer5.io](http://layer5.io/)

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by leecalcote** [comment]
Very good. Thank you, @roopeshsn. Here's a first Q&A:

**Question:** _What is the difference between the Cloud Native Playground and MeshMap?_
**Answer:** _The Cloud Native Playground (aka Meshery Playground) is a managed instance of Meshery that offers a sandbox environment in which half of MeshMap functionality is enabled (Designer mode) and the other half of MeshMap functionality is disabled (Visualizer mode).

The sandbox environment is not connected to an active Kuberentes cluster, and as such, specific actions within MeshMap Designer are also disabled. Meshery and MeshMap are feature-rich, sophisticated management applications for cloud native infrastructure. To access their full set of capabilities, simply deploy your own copy of Meshery into the environment of your choosing._

**Comment by roopeshsn** [comment]
How is this @leecalcote?

https://user-images.githubusercontent.com/70762571/219848988-36d26436-2a0b-4d96-be84-a1616fba222d.mp4

**Comment by leecalcote** [comment]
@roopeshsn, looking real good. A nice-to-have behavior is that of smoothing (easing) the transition upon closure to lessen the effect of the footer being snapped up so quickly.

**Comment by roopeshsn** [comment]
I'll take a look on that transition property, @leecalcote. Sure, I'll join the meet with open PR.
