### ISSUE TITLE
discuss.layer.io link is not specific to the card

### ISSUE THREAD

**Issue by swagataroy30** [meshery/play#69]
#### Current Behavior

When clicked outside the card, the discuss.layer5.io link gets activated - which should not be the case.

#### Expected Behavior

The link should only be activated when clicked on the card not beyond that.

#### Screenshots/Logs

https://user-images.githubusercontent.com/116095538/220164429-5b1cd64c-7bcd-4e99-a364-9c84ecdafcbe.mp4

#### Environment

- **Host OS:** Linux
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by swagataroy30** [comment]
@leecalcote i would like to work on this issue. Can you please assign me this?

**Comment by 123Vasu** [comment]
@leecalcote I have done this on my local pc. Can you Please assign me this.

**Comment by 123Vasu** [comment]
?

**Comment by leecalcote** [comment]
Thanks much, @swagataroy30, @123Vasu.

Assigning in chronological order...

**Comment by swagataroy30** [comment]
Thanks @leecalcote will make a PR soon and sorry for the late response.
