### ISSUE TITLE
Hovering of Submit Button in signup from 

### ISSUE THREAD

**Issue by 123Vasu** [meshery/play#71]
#### Current Behavior
Submit button Not Hovered like login button or signup button hover 

#### Desired Behavior
Want to Hover that Submit Button which will look good 

#### Before changes 

https://user-images.githubusercontent.com/96141990/220317431-838d23c0-2c51-4cba-9e6c-f6c0fd5813d4.mp4

#### After Changes 

https://user-images.githubusercontent.com/96141990/220317536-70f8d273-d519-49d1-a4f7-f2f6a638a157.mp4

**Comment by 123Vasu** [comment]
@leecalcote i would like to work on this issue. Can you please assign me this?

**Comment by 123Vasu** [comment]
As I have Already Done it on PC

**Comment by leecalcote** [comment]
@123Vasu, I'm just seeing this issue... after I just reviewed @Shivam164's PR. Thank you for raising this issue, @123Vasu.
