### ISSUE TITLE
Adding some basic transition effects to the various buttons on the home page.

### ISSUE THREAD

**Issue by sidtohan** [meshery/play#73]
#### Current Behavior
Right now we have some hover effects on buttons and all. But they don't have any transition effect which makes it look a little unpolished. Also the "Join our community button" still doesn't have the effect. 

#### Desired Behavior
- To add some basic transitioning to the buttons
- Add the same hover effect to the join community button

#### Implementation

- Some CSS rules need to be added.

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by leecalcote** [comment]
Great suggestion, @sidtohan. This would be nice. 👍
