### ISSUE TITLE
Remove login icon from React player alternate image and make padding consistent

### ISSUE THREAD

**Issue by vishnus17** [meshery/play#75]
#### Current Behavior
1. There is a login button inside the image displayed for the React player which is misleading. 
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/58102524/221149551-4beee036-3fd2-41dd-ac5f-2c85875434ae.png">

2. Padding is inconsistent between the React player and the text above and below it
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/58102524/221149612-6d77baac-36df-49e9-b6bc-6e4bf27eb5a5.png">

#### Desired Behavior
1. Removing the login icon.
2. Adding 3rem as margin-top for caption element similar to the other elements to make it consistent.

#### Implementation
1. Fix for issue 1
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/58102524/221149963-aa06847b-a7c7-4b65-aae2-c7359c8b7eaa.png">

2. Fix for issue 2
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/58102524/221150103-2419411f-a240-4355-8215-940c283f17e2.png">

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by vishnus17** [comment]
Hi. If you feel this needs a fix, I have it ready and I can submit the PR.

**Comment by leecalcote** [comment]
Thanks, @vishnus17. Please ensure that no image quality is lost as you edit the thumbnail.

**Comment by leecalcote** [comment]
here is the original Figma design - https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=4199%3A21678&t=p40GR93P9GDgeX6o-4

**Comment by vishnus17** [comment]
@leecalcote . I've requested access.
I used canva to add a rectangle on the thumbnail png which I got from the assets folder. The image quality seems to be intact. Shall I submit the PR so that you can review it from the preview?

**Comment by leecalcote** [comment]
Access granted. Yes, sounds good. I'm hailing @Avi-88 and @Yashsharma1911 as folks that will review.

**Comment by vishnus17** [comment]
Here's the preview link: https://deploy-preview-76--meshery-play.netlify.app
