### ISSUE TITLE
Non stop notification popup on removing everything from the canvas

### ISSUE THREAD

**Issue by Shivam164** [meshery/play#78]
#### Current Behavior
On removing all the components from the canvas, non-stop popups keep on coming up with the message "operation restricted because the canvas is empty".

#### Expected Behavior
There should only be a single popup.

#### Screenshots/Logs
[Screencast from 25-02-23 01:06:00 PM IST.webm](https://user-images.githubusercontent.com/77626594/221345399-ff45deba-fc7e-40e8-a12f-a80341d98b92.webm)

#### Environment

- **Host OS:**  Linux 
- **Platform:** Docker
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Chadha93** [comment]
Thank you @Shivam164 for reporting this bug.  // @leecalcote

**Comment by KarthikRaju391** [comment]
Hi @Shivam164, I think I can work on a fix for this.
I would like to be assigned for this issue.

**Comment by leecalcote** [comment]
@hs05june an item for you...

**Comment by leecalcote** [comment]
Fixed in v0.6.55. Thank you for reporting this, @KarthikRaju391 👍
