### ISSUE TITLE
Bug in SignUp Form

### ISSUE THREAD

**Issue by BabyElias** [meshery/play#79]
#### Current Behavior
As mentioned by Lee on Slack, there's a bug in the Name field of signup form that requires users to enter the name in a specific format.
![image](https://user-images.githubusercontent.com/95405559/221790091-a3b95944-d0b7-4994-a8bd-19a973d2c6c8.png)

#### Expected Behavior
We can either remove the check since name need not follow a specific format OR make it more inclusive to include all languages

#### Environment

- **Host OS:** Windows

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by BabyElias** [comment]
I would like to work on this issue :)

**Comment by Avi-88** [comment]
Hi @BabyElias , you can go ahead and propose a fix for this , thanks

**Comment by BabyElias** [comment]
@Avi-88 So I have come up with a regex that will declare names having punctuations,emojis and numericals as invalid, while accept letters of any language as input. Will that suit our purpose?

**Comment by Avi-88** [comment]
Cool, the invalid parts are right imo. Not sure about different languages though. Special characters - yes , but entirely different language - not sure. Any suggestions @leecalcote ?

**Comment by leecalcote** [comment]
Perhaps:

```
var re = /^[A-zÀ-Ÿ\s\d-]*$/g; 
var str1 = 'casa-me,pois 99 estou farto! Eis a lista:uma;duas;três';
var str2 = 'casa-me pois 99 estou farto Eis a lista uma duas três';
var str3 = 'àèìòùÀÈÌÒÙáéíóúýÁÉÍÓÚÝâêîôûÂÊÎÔÛãñõÃÑÕäëïöüÿÄËÏÖÜŸçÇßØøÅåÆæœ'

alert(re.test(str1));
alert(re.test(str2));
alert(re.test(str3));
```

more on this subject here - https://stackoverflow.com/questions/1073412/javascript-validation-issue-with-international-characters

**Comment by BabyElias** [comment]
> Perhaps:
> 
> ```
> var re = /^[A-zÀ-Ÿ\s\d-]*$/g; 
> var str1 = 'casa-me,pois 99 estou farto! Eis a lista:uma;duas;três';
> var str2 = 'casa-me pois 99 estou farto Eis a lista uma duas três';
> var str3 = 'àèìòùÀÈÌÒÙáéíóúýÁÉÍÓÚÝâêîôûÂÊÎÔÛãñõÃÑÕäëïöüÿÄËÏÖÜŸçÇßØøÅåÆæœ'
> 
> alert(re.test(str1));
> alert(re.test(str2));
> alert(re.test(str3));
> ```
> 
> more on this subject here - https://stackoverflow.com/questions/1073412/javascript-validation-issue-with-international-characters

This includes if not all, then a majority of international languages. So, I guess if we want to validate the names in known languages, it will work well. Should I go ahead with it @Avi-88 ?

**Comment by Avi-88** [comment]
Hi @BabyElias , sorry for the delayed response.The above mentioned one also allows numbers and whitespace , `/^[A-zÀ-Ÿ'-]+$/g` this one should deny any whitespace or numbers while allowing almost all accented letters as well. I've checked it for some names but still would suggest testing some more incase I missed anything. If everything worksout you can go ahead with it , thanks

**Comment by BabyElias** [comment]
Okay! Thank you so much :)

**Comment by BabyElias** [comment]
[A-Za-zŽžÀ-ÿ]{1,32} This is the final regex that I have come up with. Accounts for almost all the international characters check that I performed. Generating PR for the same

**Comment by BabyElias** [comment]
@Avi-88 This is the regex that I have finally come up with
([A-Za-zŽžÀ-ÿ]+('[A-Za-zŽžÀ-ÿ])?[A-Za-zŽžÀ-ÿ]){1,32}|[[A-Za-zŽžÀ-ÿ] |[A-Za-zŽžÀ-ÿ]+'{0,1}

Its a combination of 3 regexs, if any of it match to the format of our name entered, they are considered valid.
First regex :[A-Za-zŽžÀ-ÿ]+('[A-Za-zŽžÀ-ÿ])?[A-Za-zŽžÀ-ÿ]){1,32}
                  Checks for a single apostrophe which is not present at the end of or beginning but somewhere in between
Second regex: [A-Za-zŽžÀ-ÿ] 
                        The first regex should have ideally considered single characters entry as valid, but if I enter just "o" or any single
                        character, it considers it invalid, so to check single characters, we have this regex
Third regex :[A-Za-zŽžÀ-ÿ]+'{0,1}
                    If someone has their name as O'Reily, they might consider O' as their first name and Reily as last. So this regex checks if a single apostrophe is present at the end of the string (This check will only be applied to first name field and not last)

And these regexes also check for presence of accented characters, as needed originally

**Comment by Avi-88** [comment]
Woah, that's huge! <sub><sup>thats's what she said (sorry couldn't help it)</sup></sub>. Umm , I get the first 2 , but i don't think the 3rd one applies. Names with apostrophe are considered as whole and aren't split into `O'` and `Reily`. Other than that I don't have any issue with it, but could you clarify why we can't go with a much smalller regex `/^[A-zÀ-Ÿ'-]+$/g` this one instead, it's not that I want you to use what I suggested but just curious if there are advantages to using this over the other one. You can go ahead with the updated change, thanks

**Comment by BabyElias** [comment]
The regex that you have mentioned doesn't match the condition that we have just one quotation mark, and also doesn't check if that quotation mark is present in between and not at the beginning or end. 
And I'll remove the third regex then and add the regex to both first and last names.

**Comment by Avi-88** [comment]
Got it, good work @BabyElias :)
