### ISSUE TITLE
Hamburger icon not visible in dark mode in mobile view

### ISSUE THREAD

**Issue by sudhanshutech** [meshery/play#85]
#### Current Behavior

Currently, the icon is not visible due to black strokes in dark mode
![image](https://user-images.githubusercontent.com/90546692/225030464-603300f3-223b-421d-83e9-29f4e2767488.png)

#### Expected Behavior

It should have white strokes in dark mode

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by ShravaniAK** [comment]
can i work on this?
