### ISSUE TITLE
Creating a contact form to be displayed on "play.meshery.io"

### ISSUE THREAD

**Issue by roopeshsn** [meshery/play#88]
#### Desired Behavior
Creating a contact form to be displayed on [play.meshery.io](http://play.meshery.io/). The contact form component for this can be borrowed from the [layer5.io](http://layer5.io/) website.

![contact_layer5](https://user-images.githubusercontent.com/70762571/226304084-5e04c115-3ea5-43fa-b1b1-b0915e32cb8c.png)

#### Mockups
The contact form component can be found here, https://layer5.io/careers/programs#:~:text=Didn%27t%20find%20an%20answer%20to%20your%20question%3F

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by roopeshsn** [comment]
And, I would like to work on this!

**Comment by roopeshsn** [comment]
Hi, @leecalcote! What's your thought on this?

**Comment by leecalcote** [comment]
@roopeshsn, I missed this notification until now. I encourage you to ping other maintainers/contributors to increase the chances of visibility on your work. // @Shivam-AfA @ritiksaxena124 @GaganpreetKaurKalsi @asubedy @Udit-takkar

**Comment by 0xSaksham** [comment]
@Shivam-AfA @ritiksaxena124 @GaganpreetKaurKalsi @asubedy @Udit-takkar @leecalcote I can work on this issue.

**Comment by roopeshsn** [comment]
Hi, @Chadha93! I would like to know your thoughts on this issue. I am interested to work on the same!

**Comment by Udit-takkar** [comment]
hey @roopeshsn you can work on this issue but just confirm once on slack that we need this contact form here or not ?

**Comment by 8rxn** [comment]
Hey @leecalcote, if this issue is still relevant, I'd like to work on it.

**Comment by SiddheshKukade** [comment]
Hello @Chadha93, I discussed about this on the call today, I'd like to get assigned to work on this.
