### ISSUE TITLE
Update "Join the Conversation" Logos 

### ISSUE THREAD

**Issue by leecalcote** [meshery/play#90]
#### Current Behavior
In the "Join the Discussion" card, swap the Layer5 | Learn with the Meshery | Learn logo:
![meshery-learn-logo-white](https://user-images.githubusercontent.com/7570704/230503739-0eb72c85-4aeb-4dbb-ae2c-434d6785bc16.png)

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by leecalcote** [comment]
@roopeshsn

**Comment by HetviSoni** [comment]
I would like to work on this issue.

**Comment by roopeshsn** [comment]
Go a head @HetviSoni

**Comment by 0xSaksham** [comment]
Hey, I want to work on this issue. @leecalcote I found the reference, thanks!

**Comment by Chadha93** [comment]
@HetviSoni Update in this card is required - 
![image](https://user-images.githubusercontent.com/65453826/230896666-711ef3c9-ae05-4018-a5bb-33dda58202da.png)
