### ISSUE TITLE
[CI] Add PR Labeler for `area/website` for all /site/**/**

### ISSUE THREAD

**Issue by leecalcote** [meshery/play#92]
This site is missing the auto PR labeler. The workflow for this can be copied (and reduced) from the `layer5io/layer5` GitHub repo.

_Originally posted by @leecalcote in https://github.com/meshery/play/issues/91#issuecomment-1499766508_

**Comment by therajatrai** [comment]
@leecalcote Please assign this to me, would like to work on it.

**Comment by duckling69** [comment]
Hey @leecalcote it's been a month if no ones working on this issue can you assign it to me ?

**Comment by theBeginner86** [comment]
@therajatrai any update?

**Comment by duckling69** [comment]
Hey @theBeginner86 can you check if that resolves the issue

**Comment by leecalcote** [comment]
Issue assignments have gone stale. Unassigning.

Help Wanted.
