### ISSUE TITLE
[Site] Bump 150+ to 200+ integrations

### ISSUE THREAD

**Issue by leecalcote** [meshery/play#95]
A very simple request: update the following text - -

"The cloud native playground contains a set of learning paths that incorporate an application networking centric curriculum featuring training on 150+ integrations." Update to "200+"

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by HetviSoni** [comment]
Hey I would like to work on this issue.

**Comment by harshit-paneri** [comment]
Can you please assign me This Issue
