### ISSUE TITLE
Update website footer copyright year from 2022 to 2023

### ISSUE THREAD

**Issue by Savio629** [meshery/play#97]
#### Current Behavior

Update website footer copyright year from 2022 to 2023

#### Screenshots/Logs
![check3](https://user-images.githubusercontent.com/91362589/233584339-93bfcc6a-6757-44a1-a01a-8f55e6bbffa5.PNG)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by kaushik-rishi** [comment]
Can i take this up just to get started with contributing ?

**Comment by kaushik-rishi** [comment]
https://github.com/meshery/play/pull/98

**Comment by DarrenDsouza7273** [comment]
Can i work on this issue..

**Comment by Chadha93** [comment]
Hi @DarrenDsouza7273, we follow the FCFS (first come first serve) algorithm, Sinice @kaushik-rishi Commented first, let's assign this to @kaushik-rishi. @kaushik-rishi Fair warning - Next time please wait for the issue to get assigned before making a PR. 

Let's get you assigned another issue @DarrenDsouza7273.

**Comment by kaushik-rishi** [comment]
Sure @Chadha93. Next time i'll wait until i get the issue assigned.

**Comment by DarrenDsouza7273** [comment]
@Chadha93 thanks :)
